server:
  port: 0
  servlet:
    context-path: /api

spring:
  application:
    name: vehicle-service
  devtools:
    enabled: true

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka